# list of all the websites
youtube = "youtube.com"
habsnet = "https://habsnet.habsboys.org.uk/Pages/PupilPortal.aspx"
outlook = "https://outlook.office365.com/mail/inbox"
smhw = "https://www.satchelone.com/todos/issued"
amazon = "amazon.co.uk"
ebay = "ebay.co.uk"
aim_trainer = "3daimtrainer.com"
gmail = "gmail.com"
bbcBitesize = "https://www.bbc.co.uk/bitesize"
google = "www.google.com"
github = "github.com"
googleDrive = "drive.google.com"
bbc = "bbc.co.uk"
imdb = "imdb.com"
twitter = "twitter.com"
facebook = "facebook.com"
yelp = "yelp.com"
reddit = "reddit.com"
pinterest = "pinterest.com"
tripadvisor = "tripadvisor.com"
etsy = "etsy.com"
quora = "quora.com"
netflix = "netflix.com"
paypal = "paypal.com"

